id: 09aa82b6c95246f989a27ed384fc5485
initial_creation_type: ocr
source_metadata:
  volumes:
    d0e0c6e839264046881a3a50f9518d30:
      base_file: v018.txt
      image_group_id: I1PD95863
      title: སེམས་ཀྱི་སྒྲིབ་པ་རྣམ་པར་སྦྱོང་བ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1634
      volume_number: 18
